modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "curios"
version = "${version}"

[[mods]]
modId = "cclayer"
version = "${layer_version}"
displayName = "Accessories Curios Compat Layer"
authors = "Blodhgarm"
credits = "Special thanks to C4 for the creation of Curios"
description = '''
Adds Compatibility layer between Curios Based Mods and Accessories API.
'''
logoFile = "icon.png"

[[mixins]]
config = 'cclayer.mixins.json'

[[mixins]]
config = 'cclayer_curios.mixins.json'

[[dependencies.cclayer]]
modId = "neoforge"
required = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cclayer]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cclayer]]
modId = "accessories"
required = true
versionRange = "[1.0.0-beta16,)"
ordering = "NONE"
side = "BOTH"
